### ISSUE TITLE
Root access on Ifc6410 board

### ISSUE THREAD

**Issue by scdickson** [freedreno-zz/freedreno#2]
Hi, thanks for all your work on this amazing project. I'm having trouble getting past step 8 of installing Fedora and Freedreno on the Ifc6410 board. I can get to a login prompt via the serial terminal, but when I enter 'root' for the username and leave the password blank, I always receive an 'Incorrect login'. I've even tried different combinations of default usernames and passwords to no avail. Do you think I did something incorrect when setting up the Fedora file system, or is my terminal emulator maybe sending a newline character or parity bit or something else that might be interpreted as a password? Any help would be appreciated!--thanks!

**Comment by robclark** [comment]
I'm not actually sure what the password is.. seems to be different from earlier fedora filesystems.  I just mount the filesystem on my laptop and edit $ROOT/etc/shadow to remove the root password (ie. remove the stuff between the first and second ":" on the line with "root")

**Comment by scdickson** [comment]
From what I understand, an asterisk in that field means that the account is disabled and a password was never set. Is there something special I need to do to enable the root user first?

**Comment by robclark** [comment]
nope, all I've ever done is to clear whatever is between the two ":"..

**Comment by robclark** [comment]
oh, just fyi, I've added it to the FAQ too:
https://github.com/freedreno/freedreno/wiki/FAQ#wiki-rootpasswd

**Comment by scdickson** [comment]
Thanks a lot--works perfectly!
