### ISSUE TITLE
Blank Screen Starting GDM on ifc6410 board

### ISSUE THREAD

**Issue by mcclayton** [freedreno-zz/freedreno#3]
My friend and I have been independently following your steps to install Fedora and Freedreno on the Ifc6410 board. I am able to boot up Fedora and login as root via serial. Everything works fine and I even get a bootup Fedora logo through HDMI. However, the problem occurs when running 'systemctl start gdm' via the serial terminal. The screen (displaying HDMI output) just remains blank and nothing happens from here on. After some time a mouse cursor appears on the blank screen but that is all that happens. My friend and I are both stuck with this issue and any help would be greatly appreciated!

**Comment by robclark** [comment]
could be a few different things.. would help if you confirmed which userspace (mesa) and kernel you are using.

But first thing I'd try, let it sit for several minutes and see if it makes it further.  I've noticed audio driver tries to load 5 or 6 different firmware files.. and if they are missing you get a 30sec timeout for each.  Somewhere around where gdm starts (and then again when gnome-shell starts) seems to be where it attempts to start pulseaudio and hits those timeouts.

**Comment by mcclayton** [comment]
I am using the prebuilt kernel: ifc6410-boot-f20.img which I downloaded from https://github.com/freedreno/freedreno/wiki/Ifc6410 and the filesystem: Fedora-Desktop-armhfp-20-Beta-5-sda.raw.xz which I downloaded from https://github.com/freedreno/freedreno/wiki/Fedora. 

Hopefully that is the info you were asking for? 

I let it sit for quite some time (about an hour), and I still didn't see any changes. The cursor is the only thing that showed up after a few minutes. Thanks for your help by the way!

**Comment by robclark** [comment]
oh, f20 out of the box isn't going to have new enough mesa or xf86-video-freedreno.  Rawhide should have new enough versions of everything.  Or otherwise use:

http://blog.kwizart.fr/post/2014/03/02/163-mesa-10.2-from-git-for-Fedora-20

or my prebuilt userspace or build mesa and xf86-video-freedreno from src.  If using prebuilt, you may need to re-extract the tarball after an upgrade that overwrites mesa.

**Comment by mcclayton** [comment]
That was indeed the problem! Thanks so much for the help and for the incredible work you've done on this project!
