### ISSUE TITLE
IFC6410 Kernel Fails to Find Root FS After Flashing to EMMC 

### ISSUE THREAD

**Issue by akissu** [freedreno-zz/freedreno#4]
I have a IFC6410 with the Fedora kernel flashed onto the on-board eMMC boot partition. I've copied over and prepped the Fedora 20b5 FS onto a Micro SD card. Upon booting the kernel does not mount the root device at /dev/mmcblk0p3, but instead systemd attempts to mount /dev/sda3 and fails:
systemd[1]: Job dev-sda3.device/start timed out.
systemd[1]: Timed out waiting for device dev-sda3.device.
systemd[1]: Dependency failed for device dev-sda3.device. 
systemd[1]: Dependency failed for /sysroot.
systemd[1]: Dependency failed for Initrd Foot File System.
systemd[1]: Dependency failed for Reload Configuration from the Real Boot.

It seems to work only if I explicitly set bootparams on the kernel using fastboot -c. Without it, I assume initrd is pre-configured to look for sda. Is there any way I can change this? Thanks.

**Comment by robclark** [comment]
For SD card, you probably need to edit /etc/fstab (which right now is pointed at /dev/sda3).. that is why systemd is complaining.

To change the boot image to use different bootargs, you can use 'abootimg -x' to extract the existing boot img, modify the bootimg.cfg file, then then re-pack it with 'abootimg --create my-ifc6410-boot.img -k ./zImage -f ./bootimg.cfg -r ./initrd.img' (double check the initrd name.. easiest just to extract to an empty directory.

**Comment by akissu** [comment]
Thanks for the quick reply! Your answer was exactly what I was looking for.
